### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by jeandeaual** [esrille/new-keyboard#16]
First, I'd like to thank you for the great keyboard and firmware.

The steps to build the project described in the [FAQ](https://www.esrille.com/keyboard/faq.html#q-firmware-customize) are very clear, but it would be nice if that process was automated. What do you think?
Since the source code is hosted on a public repository, you can use [GitHub Actions](https://github.com/features/actions) or [Travis CI](https://travis-ci.org/) for free.

This would allow anyone cloning the repository to build their changes without having to install MPLAB X and XC8, automatically check if every firmware can be built when pushing code or creating a pull request, or automate the release process if you wish so.

I already have a working GitHub Action [here](https://github.com/jeandeaual/new-keyboard/blob/feature/github-action/.github/workflows/build.yml) for example, which builds firmware versions 1.09 / 0.27 on push and PR on all branches (but can be restricted to master only) and generates a draft release on GitHub with the built firmware files when creating a Git tag. The result is [here](https://github.com/jeandeaual/new-keyboard/actions/runs/745307733) (see the "Artifacts" tab for the generated firmware files). The generated files are exactly the same as the ones available for download on [your website](https://www.esrille.com/keyboard/ja-jp/support.html).

**Comment by ShikiOkasaka** [comment]
Automated build systems will not be enabled with this repository.
The actual test steps still need to be done using the NISSE keyboards at this point.
