### ISSUE TITLE
__EEPROM_DATA and initKeyboardBase: mode (EEPROM_BASE) is always set to 0

### ISSUE THREAD

**Issue by listx** [esrille/new-keyboard#8]
It looks like eeprom_read() always returns 0xff (I researched a bit and this is the default return value if things are not set right). I tried setting

```
__EEPROM_DATA(BASE_QWERTY, KANA_ROMAJI, OS_PC, 1 /* delay */, 0 /* mod */, LED_DEFAULT, IME_MS, 0 /* mouse */);

```

to

```
__EEPROM_DATA(BASE_DVORAK, KANA_ROMAJI, OS_PC, 1 /* delay */, 0 /* mod */, LED_DEFAULT, IME_MS, 0 /* mouse */);

```

and I get

```
esrille nisse
rev. 5
ver. 0.17
copyright 2013-2015 esrille inc.
f2 pc
f3 us
f4 roma
f5 d0
f6 c
f7 ms
f8 c-c
f9 off
```

where `f3 us` should be `f3 us-d`. I.e., in `KeyboardUS.c`, the `if` block in

```
    mode = eeprom_read(EEPROM_BASE);
    if (BASE_MAX < mode)
        mode = 0;
```

is somehow evaluating and setting it back to 0 (BASE_QWERTY).

This is not a serious issue because the FN+F3 command (`switchBase()`) works fine.

I've actually done a workaround, which is to simply change `initKeyboardBase()` from

```
void initKeyboardBase(void)
{
    mode = eeprom_read(EEPROM_BASE);
    if (BASE_MAX < mode)
        mode = 0;
}
```

to

```
void initKeyboardBase(void)
{
    mode = BASE_DVORAK;
}
```

. I'm on Mac, using the newer MLA as stated here https://github.com/esrille/new-keyboard/issues/7#issuecomment-152823751 .

I also noticed that we define `static uint8_t mode;` twice, once in `KeyboardUS.c` and also in `KeyboardJP.c`. (I just thought it was weird).

For sanity purposes I did diffs against the various `.hex` produced files, and they look fine; e.g., the EEPROM data part looks like

```
... (truncated)
:080000000100000100040000F2
          ^     ^   ^
... (truncated)
```

where the bits marked `^` correspond neatly to the __EEPROM_DATA macro declaration

```
__EEPROM_DATA(BASE_DVORAK, KANA_ROMAJI, OS_PC, 1 /* delay */, 0 /* mod */, LED_DEFAULT, IME_MS, 0 /* mouse */);
```

(BASE_DVORAK is 1, delay is 1, and LED_DEFAULT is 4).

Thoughts?

**Comment by listx** [comment]
To clarify: the problem is that the initial state of the keyboard, after being flashed with the changed .hex file, does not reflect what was set in __EEPROM_DATA. As I stated above, it's not a huge problem because there is a workaround, but at the same time this basically means that we are not making use of the EEPROM data when we first connect the device after a firmware change.

**Comment by ShikiOkasaka** [comment]
To program EEPROM with the USB Bootloader, please select the **Settings...** menu item from the **Program** menu, and check the **EEPROM** checkbox in the **Settings** dialog box. Seciton **1.6.3 Device - Boot Loader - HID** in Microchip Libraries for Applications (MLA)'s document  "**USB Library**" contains further details.

ps. In the C programming language, variables declared with "static" at the top level of a file have file scope:
https://en.wikipedia.org/wiki/Scope_%28computer_science%29#File_scope

**Comment by listx** [comment]
It worked!

I am using v2.13 of HIDBootloader, and I had to click on HIDBootloader, Preferences, and then click on the EEPROM checkbox (it was unchecked). I just reflashed using a firmware that did not have my hardcoded workaround and it detected the correct layout.

Thanks again!
